### ISSUE TITLE
NSS build breaks with v0.5

### ISSUE THREAD

**Issue by bourgeoa** [nodeSolidServer/jose#8] opened 2020-03-01 10:21 UTC
I am building a new docker NSS 5.2.3 to test a patch, and I got the following compile error : 

```
> solid-server@5.2.3 solid /usr/src/app
> node ./bin/solid "start"

/usr/src/app/node_modules/@solid/cli/node_modules/@solid/oidc-rp/lib/IDTokenSchema.js:14
var IDTokenSchema = JWTSchema.extend({
                              ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (/usr/src/app/node_modules/@solid/cli/node_modules/@solid/oidc-rp/lib/IDTokenSchema.js:14:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@solid/cli/node_modules/@solid/oidc-rp/lib/IDToken.js:17:21)
    at Module._compile (module.js:652:30)

``` 

IDTokenSchema.js lead me to @solid/jose

```
'use strict';

/**
 * Local dependencies
 */
var _require = require('@solid/jose'),
    JWTSchema = _require.JWTSchema;

/**
 * IDToken Schema
 */


var IDTokenSchema = JWTSchema.extend({
  properties: {

    /**

```

JWTSchema as been deleted from @solid/jose v0.5

`https://github.com/solid/jose/commit/f0a7e84c477052df45450fe945308decf801b2e4#diff-1e355bcfa499b1b7230ac4128dec5f19`

**Comment by dmitrizagidulin** [comment] 2020-03-03 22:38
This is not an issue with this repo, `@solid/jose`. 

The issue is in the https://github.com/solid/solid-cli/ repo. It needs to publish a new npm version that includes Ruben's fix, https://github.com/solid/solid-cli/commit/8aaf55e76c2ee4712c47230726f66577fc4b0535.

Then you need to update `solid-auth-cli`, then update `rdflib`, and finally update NSS to use that rdflib.

Closing this issue.

**Closed as completed by dmitrizagidulin** 2020-03-03 22:38 UTC
Labels: regression
